const Theatres = [
  {
    id: 0,
    name: 'L.A Cinemas',
    address:
      ' Maris Theater Complex, Fort Station Rd, Tiruchirappalli, Tamil Nadu 620002',
    pic: require('../assets/LACinemas.jpg'),
    dates: [
      { month: 'April', date: '01' },
      { month: 'April', date: '02' },
      { month: 'April', date: '03' },
      { month: 'April', date: '04' },
      { month: 'April', date: '05' },
      { month: 'April', date: '06' },
    ],
    showTiming: [
      '8:00 AM',
      '11:15 AM',
      '2:30 PM',
      '4:15 PM',
      '6:45 PM',
      '8:00 PM',
      '10:30 PM',
    ],
    seatData: [
      'A1',
      'A2',
      'A3',
      'A4',
      'A5',
      'A6',
      'A7',
      'B1',
      'B2',
      'B3',
      'B4',
      'B5',
      'B6',
      'B7',
      'C1',
      'C2',
      'C3',
      'C4',
      'C5',
      'C6',
      'C7',
      'D1',
      'D2',
      'D3',
      'D4',
      'D5',
      'D6',
      'D7',
      'E1',
      'E2',
      'E3',
      'E4',
      'E5',
      'E6',
      'E7',
      'F1',
      'F2',
      'F3',
      'F4',
      'F5',
      'F6',
      'F7',
      'G1',
      'G2',
      'G3',
      'G4',
      'G5',
      'G6',
      'G7',
    ],
  },
  {
    id: 1,
    name: 'Megastar Cinemas',
    address:
      'Salai Road Tiruchirappalli No 150/74 D1, Tiruchirappalli, Tamil Nadu 620018',
    pic: require('../assets/Megastar.jpg'),
    showTiming: [
      '8:00 AM',
      '11:15 AM',
      '2:30 PM',
      '4:15 PM',
      '6:45 PM',
      '8:00 PM',
      '10:30 PM',
    ],
    dates: [
      { month: 'April', date: '01' },
      { month: 'April', date: '02' },
      { month: 'April', date: '03' },
      { month: 'April', date: '04' },
      { month: 'April', date: '05' },
      { month: 'April', date: '06' },
    ],
    seatData: [
      'A1',
      'A2',
      'A3',
      'A4',
      'A5',
      'A6',
      'A7',
      'B1',
      'B2',
      'B3',
      'B4',
      'B5',
      'B6',
      'B7',
      'C1',
      'C2',
      'C3',
      'C4',
      'C5',
      'C6',
      'C7',
      'D1',
      'D2',
      'D3',
      'D4',
      'D5',
      'D6',
      'D7',
      'E1',
      'E2',
      'E3',
      'E4',
      'E5',
      'E6',
      'E7',
      'F1',
      'F2',
      'F3',
      'F4',
      'F5',
      'F6',
      'F7',
      'G1',
      'G2',
      'G3',
      'G4',
      'G5',
      'G6',
      'G7',
      'H1',
      'H2',
      'H3',
      'H4',
      'H5',
      'H6',
      'H7',
    ],
  },
  {
    id: 2,
    name: 'L.A Sona Mina',
    address:
      '8 G, Williams Rd, Cantonment (Near Central Bus Stand, 7c, Williams Rd, beside sona mina theatre, Cantonment, Tiruchirappalli, Tamil Nadu 620001',
    pic: require('../assets/sonamina.jpg'),
    showTiming: [
      '8:00 AM',
      '11:15 AM',
      '2:30 PM',
      '4:15 PM',
      '6:45 PM',
      '8:00 PM',
      '10:30 PM',
    ],
    dates: [
      { month: 'April', date: '01' },
      { month: 'April', date: '02' },
      { month: 'April', date: '03' },
      { month: 'April', date: '04' },
      { month: 'April', date: '05' },
      { month: 'April', date: '06' },
    ],
    seatData: [
      'A1',
      'A2',
      'A3',
      'A4',
      'A5',
      'A6',
      'A7',
      'B1',
      'B2',
      'B3',
      'B4',
      'B5',
      'B6',
      'B7',
      'C1',
      'C2',
      'C3',
      'C4',
      'C5',
      'C6',
      'C7',
      'D1',
      'D2',
      'D3',
      'D4',
      'D5',
      'D6',
      'D7',
      'E1',
      'E2',
      'E3',
      'E4',
      'E5',
      'E6',
      'E7',
      'F1',
      'F2',
      'F3',
      'F4',
      'F5',
      'F6',
      'F7',
    ],
  },
];

export default Theatres;
